### ISSUE TITLE
Unity MacOS error: Drawing with MeshTopology.Points, yet the vertex program 'Hidden/OpaqueSelection' does not have PSIZE output.

### ISSUE THREAD

**Issue by svjetlonosha141** [keijiro/Pcx#71] opened 2021-07-07 03:02 UTC
Hi Keijiro,
First of all - HUGE thank you for all the work you've put into this, I really appreciate it. 

I am currently working on a VR project using Unity and came across a problem that appears only on MacOS. 
Apologies if this issue already came up - I went through all of them and couldn't find anyone mentioning this nor providing a solution. Please see the details of the error below. 
Any help is more than welcome!
Cheers

I successfully imported my point cloud on Windows, but this error keeps appearing when trying to do the same in MacOS. Point cloud is successfully imported as mesh but instead of points, i get these rectangles and a very  low quality. 

"Drawing with MeshTopology.Points, yet the vertex program 'Hidden/OpaqueSelection' does not have PSIZE output."
<img width="835" alt="Screen Shot 2021-07-07 at 12 52 12 pm" src="https://user-images.githubusercontent.com/87052160/124693890-87cadb00-df23-11eb-9528-1e456db30932.png">

System details:
macOS: Big Sur
GPU: AMD Radeon Pro 5500M
Metal Family: Metal GPUFamily macOS 2
Unity: 2020.3.12f1 

<img width="783" alt="Screen Shot 2021-07-07 at 12 52 00 pm" src="https://user-images.githubusercontent.com/87052160/124693789-5baf5a00-df23-11eb-8ac7-3bedb52608da.png">

**Comment by keijiro** [comment] 2021-07-07 03:17
Those warning messages are caused by the Scene View. It doesn't affect the quality of rendering. Please ignore them.

**Comment by keijiro** [comment] 2021-07-07 03:17
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed as completed by keijiro** 2021-07-07 03:17 UTC
Labels: question

**Comment by svjetlonosha141** [comment] 2021-07-07 05:10
Thanks for a quick reply. Will ignore the warning then.
But do you maybe know how I can change this view so I can actually see points instead of these ugly rectangles? i am not able to see much details even when in game view...
Sorry if it's a silly question, I'm a beginner...

Thanks.

**Comment by keijiro** [comment] 2021-07-07 06:26
Try disabling "Apply Distance". See "Rendering Methods" on README.

**Comment by svjetlonosha141** [comment] 2021-07-07 06:29
Thanks, problem solved, managed to get the points by playing with the mesh renderer and different materials.

**Comment by sep-sabeti** [comment] 2022-03-08 15:02
Could you elaborate how you solved it? I am having the same issue !

**Comment by svjetlonosha141** [comment] 2022-05-02 10:10
Hi Sep,
Sorry for a super late reply, but I am traveling and hence slack with emails and don't have access to Unity at the moment. From what I can remember, this issue was easily resolved by literally just changing the way Unity renders the point cloud. When you click on the point cloud in the scene (or down in the project files), the inspector should offer you different ways of rendering and "default point" option should be picked
Hope that helps, sorry I couldn't provide any screenshots

**Comment by tokuuuu** [comment] 2022-05-13 07:21
I can't change "Apply Distance".
Property is grayed out.

Unity 2020.3.33

**Comment by tokuuuu** [comment] 2022-05-16 04:29
I could indicate ".Ply" data.

Unity 2019.4.39

Thanks.
