### ISSUE TITLE
More efficient dynamic pointcloud

### ISSUE THREAD

**Issue by Changliu52** [keijiro/Pcx#42] opened 2019-12-04 18:18 UTC
We have gotten the pointcloud working by rerender it completely every loop. It works fine. https://github.com/keijiro/Pcx/issues/29

Now the performance is not fast enough. We want to be able to use Initialise() to update a fixed size pointcloud.

Could you give us some suggestions on how we can modify the library? Or what is stopping h us from doing so?

Best Regards,
Chang

**Comment by keijiro** [comment] 2019-12-05 01:14
The editor functions of PointCloudData are not optimized for runtime use, so it would become a bottleneck if you dynamically use it.

There are some optimization ideas:

- EncodeColor should be done in a compute shader. It could be over 10 times faster than the current C# implementation.
- There is a hack-ish technique to avoid array copy when initializing a compute buffer: https://github.com/keijiro/Rsvfx/blob/master/Assets/Rsvfx/Runtime/Utility.cs#L18

By the way, how do you use it? I wonder what kind of point cloud you're trying to handle with it.

**Comment by Changliu52** [comment] 2019-12-05 07:16
We are trying to display realsense pointcloud through wireless communication.
The pointcloud renderer in realsense sdk works really fast if we connect realsense directly to PC.

Maybe there are something in the realsense sdk we can borrow?

Chang

**Comment by keijiro** [comment] 2019-12-05 08:12
I think there is no merit in using Pcx for that purpose. It might be easier to bake a point cloud into a texture and render it using VFX Graph. In this case, the only problem is that how you transfer the texture via a wireless connection. Wi-Fi is far slower than USB 3.1 Gen 1, so the bandwidth gap would cause a problem.

**Comment by keijiro** [comment] 2019-12-05 08:12
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed by keijiro** 2019-12-05 08:12 UTC
Labels: question

**Comment by Changliu52** [comment] 2019-12-11 22:42
I intend to use pcx just to rendering the pointcloud. We have manage to stream the pointcloud over WiFi and render with the current version pcx. Yes, the bandwidth is one problem, but we already tried to use cable connection and same method to render and It is still very slow. We are tying to optimise through both directions. I saw this https://github.com/IntelRealSense/librealsense/blob/master/wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RsPointCloudRenderer.cs from realsense SDK which renders the points super fast in our test. Maybe there are something we can directly borrow from there?

**Comment by keijiro** [comment] 2019-12-16 07:54
Okay. So the bandwidth is not a problem. Then the root cause is quite clear: There is a bottleneck in the `PointCoudData.Initialize` code.

> I saw this https://github.com/IntelRealSense/librealsense/blob/master/wrappers/unity/Assets/RealSenseSDK2.0/Scripts/RsPointCloudRenderer.cs from realsense SDK which renders the points super fast in our test. Maybe there are something we can directly borrow from there?

No. It can't get faster unless solving the bottleneck. If you optimize the Initialize function, it will run faster than `RsPointCloudRenderer`.

My recommendation is migrating to VFX Graph. You don't need to use Pcx in this case. VFX Graph can handle tons of points without hassle.
