### ISSUE TITLE
Separate the conversion positions/colors -> Point[] from the _pointData assignment in Initialize(List<Vector3>, List<Color32>)

### ISSUE THREAD

**Issue by masmil1988** [keijiro/Pcx#49] opened 2020-02-12 10:57 UTC
I have a lot of point clouds with a lot of points to render at runtime. In order to avoid to overload the main thread I perform the most of my calculations in a secondary thread; when points are ready to be rendered I call PointCloudData.Initialize by passing the points positions and colors.

This method needs to be called on the main thread. If I have a lot of points this method locks the main thread until all points have been put into a Point[] array.
This conversion can still be done in a secondary thread, so that when the PointCloudData has to be initialized this operation can be done by passing already prepared data.

I modified your library by adding a method PreparePoints(List<Vector3> positions, List<Color32>) which returns a Point[].

```
public static Point[] PreparePoints(List<Vector3> positions, List<Color32> colors)
{
	PointCloudData.Point[] points = new Point[positions.Count];
	for (int i = 0; i < positions.Count; i++)
	{
		points[i] = new Point
		{
			position = positions[i],
			color = EncodeColor(colors[i])
		};
	}

	return points;
}

public void Initialize(Point[] points)
{
	_pointData = points;
}
```

**Comment by keijiro** [comment] 2020-02-12 13:04
I think that's a good solution for your problem. By the way, what's the point of this issue? I think this is not a bug report nor a technical question.

**Comment by keijiro** [comment] 2020-02-18 00:45
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed by keijiro** 2020-02-18 00:45 UTC
Labels: question
